### ISSUE TITLE
Some transcript pathways p values seem missing.

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/GraphOmics#27] opened 2019-12-04 16:31 UTC
Sometimes the p-values for a transcript pathway analysis are missing, even though a given transcript is on the pathway. See screenshot for example. If this is a least one transcript on the pathway, shouldn't there also be a p-value?
<img width="2903" alt="Screenshot 2019-12-04 at 16 29 50" src="https://user-images.githubusercontent.com/6143277/70161041-5a68dc00-16b3-11ea-9f89-ecfdfe5331e1.png">

**Comment by joewandy** [comment] 2020-01-13 10:53
This was caused by a bug in PALS where only metabolic pathways from reactome are used for transcript & protein analysis (and non-metabolite pathways are ignored). Fixed in https://github.com/glasgowcompbio/PALS/commit/3c2b4af1b971cf21331f706a3e723694dead2efc.

To get the correct data in WebOmics:
1. Update pals `pipenv update pals-pathway`. Make sure version number in Pipfile.lock is ==1.1.5
2. Re-run pathway analysis. It will overwrite the previously incorrect results.

**Closed as completed** 2020-02-24 12:25 UTC
