### ISSUE TITLE
Error 400 when uploading file

### ISSUE THREAD

**Issue by joewandy** [glasgowcompbio/GraphOmics#118] opened 2022-01-27 13:00 UTC
Jan 27 12:51:07 benford pipenv[123313]: 2022-01-27 12:51:07.178 | INFO     | linker.views.functions:save_analysis:317 ->
Jan 27 12:51:07 benford pipenv[123313]: 2022-01-27 12:51:07.215 | INFO     | linker.views.functions:save_analysis:317 ->
Jan 27 12:51:07 benford pipenv[123313]: 2022-01-27 12:51:07.283 | INFO     | linker.views.functions:save_analysis:317 ->
Jan 27 12:51:07 benford pipenv[123313]: 2022-01-27 12:51:07.787 | INFO     | linker.views.functions:save_analysis:317 ->
Jan 27 12:51:07 benford pipenv[123313]: 2022-01-27 12:51:07.911 | INFO     | linker.views.functions:save_analysis:317 ->
Jan 27 12:51:07 benford pipenv[123313]: 2022-01-27 12:51:07.984 | INFO     | linker.views.functions:save_analysis:317 ->
Jan 27 12:51:08 benford pipenv[123313]: django.security.SuspiciousFileOperation ERROR 2022-01-27 12:51:07,995 exception>
Jan 27 12:51:08 benford pipenv[123313]: django.request WARNING 2022-01-27 12:51:08,055 log.py:224 | Bad Request: /app/l>

**Comment by RonanDaly** [comment] 2024-05-30 22:55
This was caused by an update to django. Fixed in commit 575d03f.

**Closed as completed by RonanDaly** 2024-05-30 22:55 UTC
Labels: bug
