### ISSUE TITLE
Data is being stored inefficiently

### ISSUE THREAD

**Issue by RonanDaly** [glasgowcompbio/GraphOmics#52] opened 2020-05-26 11:57 UTC
We are storing the data and other information as serialised strings. This has cascading effects with deletion etc. which mean multiple versions need to kept. This has meant that the database is growing extremely quickly, which probably isn't feasible when more users come on board. Need to replace with proper database schema via django.

**Comment by joewandy** [comment] 2020-05-28 12:31
It's actually not that bad, let me explain. Apologies for the wall-of-text.

1. Users create an analysis. This is stored in the [Analysis](https://github.com/glasgowcompbio/WebOmics/blob/master/web_omics/linker/models.py#L14-L55) model.

2. For every data type (transcriptomics, proteomics, metabolomics, reactions, pathways), an [AnalysisData](https://github.com/glasgowcompbio/WebOmics/blob/master/web_omics/linker/models.py#L14-L55) model is created. 
    - An `AnalysisData` is linked to an `Analysis` . 
    - Each `AnalysisData` also has a parent `AnalysisData` that it originates from (set to None if it's the first after uploading), as well as other fields like the data type (transcript, protein, metabolite etc), the inference type that creates it, metadata, timestamp etc. 
    - Additionally the entire dataframe associated with this `AnalysisData` is stored in the `json_data` field in a serialised JSON format.

3. When users or system runs an inference, an entire new `AnalysisData` for that data type is created. Depending on the inference task, the new results can be stored either in the `json_data` (as part of the dataframe) or in the metadata field. For example, the t-test inference task stores the p-value and the fold-change in the dataframe, while clustergrammer stores the cluster info in the metadata. 
    - By design each time a `AnalysisData` is created, we try to make sure that it contains all the data copied from the parent in the json field or in the metadata, PLUS any additional new data that we are adding. No information is lost as the latest `AnalysisData` contains everything we need. **This is where data duplication happens since none of the parents are deleted.** 
    - On the front-end, only the latest `AnalysisData` is shown to the user.
    - Pros of this design: no joins (fast to retrieve), easy to undo inference (just by deleting one record in the db), easy to retrieve results for analysis outside in e.g. notebooks (just load the dataframe from the db).
    - Cons of this design: uses up a lot of storage *if we are tracking all the histories*.
    - Why not turn all these into a full relational data instead of just dumping the entire df into JSON? Because joins are slow, and the data never changes. I suppose we can create (database) views to speed things up, but that's still some work to assemble database query results into a dataframe for use in analysis.

4. **A quick workaround that balances above pros/cons:** 
    - Don't store the big stuff (dataframe, metadata) in the parents, only store them in the latest `AnalysisData`. 
    - Or we can simply get rid of this parent-child relationship in `AnalysisData` and retains only the last one. What do you think?

**Comment by RonanDaly** [comment] 2020-05-28 13:50
Here are the possible problems as I see them (they might not be actual problems when running):

- We are repeatedly re-storing data after every inference. This will give us storage requirements in O(n^2), which is not feasible. I feel this definitely has to change in some way.
- We are storing data in a non-efficient format, as serialised objects. I'm not sure what the overhead of this is, I'd have to look into it a bit more.
- We are storing blobs of data in an RDBMS. For performance reasons, it might be more beneficial to store the blobs directly on the filesystem.

**Comment by RonanDaly** [comment] 2020-05-28 13:51
Quick question, what would happen if we wanted to delete an inference further back the chain. E.g. if there are 5 inferences and we want to delete number 2 and keep the rest, does the current model work okay?

**Comment by RonanDaly** [comment] 2020-05-28 13:53
Can we have `AnalysisData` simply store each inference and have everything merged when performing the view. If we guarantee that the order of items doesn't change, then it would be equivalent to concatenating columns which is very quick. We could also easily delete an inference.

**Comment by joewandy** [comment] 2020-05-28 21:03
> Quick question, what would happen if we wanted to delete an inference further back the chain. E.g. if there are 5 inferences and we want to delete number 2 and keep the rest, does the current model work okay?

No. 2 will disappear from the list of past inferences (from the Inference tab). However its results are already carried forward as part of no. 3, 4 and 5.

**Comment by joewandy** [comment] 2020-05-28 21:03
> Can we have `AnalysisData` simply store each inference and have everything merged when performing the view. If we guarantee that the order of items doesn't change, then it would be equivalent to concatenating columns which is very quick. We could also easily delete an inference.

I like this suggestion! Let's go with this 😀

When deleting something in the middle of a chain, I guess we have to update the parent pointer to point to the correct one .. but that's doable.

**Comment by RonanDaly** [comment] 2020-05-29 15:07
It doesn't need to be a chain anymore though, it would be a set I think. Which makes maintenance of everything much easier.

**Comment by RonanDaly** [comment] 2020-06-01 13:41
Possibility to compress serialised objects? Don't know if this would store okay in database. Does sqlLite have a binary type?

**Comment by joewandy** [comment] 2020-06-01 14:11
There's [a JSON extension](https://www.sqlite.org/json1.html) for sqlite, but for backward compatibility, it still stores things as text anyway in the database.

At the moment, we're using [this](https://pypi.org/project/jsonfield/) to store the JSON in a database-independent way from django.

**Comment by joewandy** [comment] 2020-08-19 14:29
Fixed in https://github.com/glasgowcompbio/WebOmics/pull/71

**Comment by RonanDaly** [comment] 2020-08-19 16:10
I think we really need the delete functionality. I'm going to have a look over things to see what's possible.

**Comment by RonanDaly** [comment] 2020-08-19 21:25
`get_updated_json_data` seems to merge results in json data. Is this very slow? If not, then this could work on the fly.

**Comment by joewandy** [comment] 2020-08-19 21:48
Will do some timing later to determine how fast `get_updated_json_data` runs (seems like it should be pretty fast?). That works for t-tests, limma, deseq.

For pathway stuff (PLAGE, ORA, GSEA), the equivalent of `get_updated_json_data` is [update_pathway_analysis_data](https://github.com/glasgowcompbio/WebOmics/blob/64c1042310db3a45ce9f0c16dda1faad71435f87/web_omics/linker/views/inference_view.py#L566).

For Reactome analysis, the results are instead stored in the [metadata](https://github.com/glasgowcompbio/WebOmics/blob/64c1042310db3a45ce9f0c16dda1faad71435f87/web_omics/linker/views/inference_view.py#L739-L744
) field of the `AnalysisData` model (together with clustergrammer results, which is unchanged once it's initialised).

If we want to do this, I think we can still keep the base results (initial dataframe + metadata) in the `json_data` and `metadata` fields of [AnalysisData](https://github.com/glasgowcompbio/WebOmics/blob/64c1042310db3a45ce9f0c16dda1faad71435f87/web_omics/linker/models.py#L91-L97). Then we store the individual inference results in the [AnalysisHistory](https://github.com/glasgowcompbio/WebOmics/blob/64c1042310db3a45ce9f0c16dda1faad71435f87/web_omics/linker/models.py#L112-L117) model. Finally we need a merge procedure that brings the base results + individual results together. I'll give that a try later.

**Comment by RonanDaly** [comment] 2020-08-19 21:55
Yes, instead of storing in AnalysisData after inference, we store in AnalysisHistory. Then at fetch, we iterate over inferences for species, pathways and Reactome and merge. Just a thought, currently the individual results are not jsonified, I guess this would have to happen to store in database - still should be quick to pull out and put in overall json_data.

**Comment by RonanDaly** [comment] 2020-08-19 21:56
Just wondering, why is the pathway stuff separate - is it because there is no idea of fold change?

**Comment by joewandy** [comment] 2020-08-28 12:13
It's because PALS produce output in a different format than what the other inference methods (e.g. t-test, limma) produce. Also yeah there's no fold change column in the PALS output.

**Comment by joewandy** [comment] 2020-08-28 12:53
> Yes, instead of storing in AnalysisData after inference, we store in AnalysisHistory. Then at fetch, we iterate over inferences for species, pathways and Reactome and merge. Just a thought, currently the individual results are not jsonified, I guess this would have to happen to store in database - still should be quick to pull out and put in overall json_data.

Submitted a big pull request #74 for this

**Closed as completed** 2021-03-25 15:56 UTC
Labels: manuscript, priority
